'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DotaHeroFilter.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property abaddon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abaddon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property alchemist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alchemist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ancient_apparition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancient_apparition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property antimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("antimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property arc_warden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arc_warden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property axe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("axe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property batrider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("batrider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property beastmaster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beastmaster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bloodseeker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bloodseeker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bounty_hunter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bounty_hunter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brewmaster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brewmaster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property bristleback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bristleback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property broodmother() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("broodmother", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property centaur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("centaur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property chaos_knight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chaos_knight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property chen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property clinkz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clinkz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property clockwerk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clockwerk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property crystal_maiden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crystal_maiden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dark_seer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dark_seer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dark_willow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dark_willow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;Data&gt;
        '''  &lt;Heroes&gt;
        '''    &lt;Hero name=&quot;Abaddon&quot;&gt;
        '''      &lt;Tag name=&quot;Melee&quot;&gt;&lt;/Tag&gt;
        '''      &lt;Tag name=&quot;Offlane&quot;&gt;&lt;/Tag&gt;
        '''    &lt;/Hero&gt;
        '''    &lt;Hero name=&quot;Alchemist&quot;&gt;
        '''      &lt;Tag name=&quot;Melee&quot;&gt;&lt;/Tag&gt;
        '''      &lt;Tag name=&quot;Safelane&quot;&gt;&lt;/Tag&gt;
        '''      &lt;Tag name=&quot;Mid&quot;&gt;&lt;/Tag&gt;
        '''    &lt;/Hero&gt;
        '''    &lt;Hero name=&quot;Ancient_Apparition&quot;&gt;
        '''      &lt;Tag name=&quot;Ranged&quot;&gt;&lt;/Tag&gt;
        '''      &lt;Tag name=&quot;Support&quot;&gt;&lt;/Tag&gt;
        '''    &lt;/Hero&gt;
        '''    &lt;Hero name=&quot;AntiMage&quot;&gt;
        '''      &lt;Tag name=&quot;Melee&quot;&gt;&lt;/Tag&gt;
        '''      &lt;Tag name=&quot;Safelane&quot;&gt;&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Data() As String
            Get
                Return ResourceManager.GetString("Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dazzle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dazzle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property death_prophet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("death_prophet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property disruptor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disruptor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property doom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dragon_knight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dragon_knight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property drow_ranger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drow_ranger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property earth_spirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earth_spirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property earthshaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earthshaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property elder_titan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elder_titan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ember_spirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ember_spirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property enchantress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enchantress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property enigma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enigma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property faceless_void() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("faceless_void", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property fade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property furion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("furion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property gyrocopter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gyrocopter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property highlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("highlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property huskar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("huskar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property invoker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property io() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("io", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property jakiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jakiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property juggernaut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("juggernaut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property keeper_of_the_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keeper_of_the_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property kunkka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kunkka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property legion_commander() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legion_commander", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property leshrac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leshrac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lich() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lich", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lifestealer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lifestealer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lone_druid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lone_druid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property luna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property lycan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lycan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property magnus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property medusa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medusa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property meepo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meepo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mirana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mirana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property monkey_king() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monkey_king", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property morphling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("morphling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property naga_siren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("naga_siren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property necrophos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("necrophos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property night_stalker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("night_stalker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property nyx_assassin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nyx_assassin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ogre_magi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ogre_magi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property omniknight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("omniknight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property oracle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oracle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property outworld_devourer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outworld_devourer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property pangolier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pangolier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property phantom_assassin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phantom_assassin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property phantom_lancer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phantom_lancer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property phoenix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phoenix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property puck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property pudge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pudge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property pugna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pugna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property queen_of_pain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queen_of_pain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property razor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("razor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property riki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("riki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rubick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rubick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sand_king() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sand_king", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property shadow_demon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_demon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property shadow_fiend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_fiend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property shadow_shaman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow_shaman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property silencer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silencer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property skywrath_mage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skywrath_mage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property slardar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slardar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property slark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sniper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property spectre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spectre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property spirit_breaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spirit_breaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property storm_spirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("storm_spirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sven() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sven", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property techies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("techies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property templar_assassin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("templar_assassin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property terrorblade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("terrorblade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property tidehunter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tidehunter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property timbersaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("timbersaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property tinker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tinker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property tiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property treant_protector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treant_protector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property troll_warlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("troll_warlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property tusk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tusk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property underlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property undying() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undying", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ursa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ursa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property vengeful_spirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vengeful_spirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property venomancer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("venomancer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property viper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property visage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("visage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property warlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property weaver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property windranger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windranger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property winter_wyvern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("winter_wyvern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property witch_doctor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("witch_doctor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property wraith_king() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wraith_king", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property zeus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zeus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
